markdown: kramdown
highlighter: rouge
permalink: /posts/:title.html
excerpt_separator: "<!-- more -->"

author: "Haoyuan Zhang"
email: haoyuan.zhang@qmul.ac.uk
name: "Haoyuan Zhang"
url: haoyuanzhang1990.github.io
all_categories: [
["pub", "Publication","pub.html"], 
["researchandteaching", "Research and Teaching","randt.html"],
["knife", "Codes","knife.html"]
]

paginate: 4
paginate_path: "posts/page:num"
timezone: Europe/London

collections:
  docs:
    output: true

gems:
 - jekyll-paginate
